{
 "title": "Near Node Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "account_id",
    "query": {
     "query": "label_values(near_validators_blocks_expected, account_id)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(near_is_validator, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_validators_blocks_produced{account_id=\"$account_id\",job=\"$job\"} / near_validators_blocks_expected{account_id=\"$account_id\",job=\"$job\"}",
     "legendFormat": "Blocks"
    },
    {
     "expr": "near_validators_chunks_produced{account_id=\"$account_id\",job=\"$job\"} / near_validators_chunks_expected{account_id=\"$account_id\",job=\"$job\"}",
     "legendFormat": "Chunks"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "near_peer_connections_total{job=\"$job\"}",
     "legendFormat": "Peers"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\"}[1m])) by (job) / count(node_cpu_seconds_total{mode=\"user\"}) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Is Validator",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "near_is_validator{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Is Validator",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "targets": [
    {
     "expr": "near_is_validator{job=\"$job\"}",
     "legendFormat": "State"
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "near_validators_chunks_expected{account_id=\"$account_id\",job=\"$job\"}",
     "legendFormat": "Expected"
    },
    {
     "expr": "near_validators_chunks_produced{account_id=\"$account_id\",job=\"$job\"}",
     "legendFormat": "Produced"
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "near_validators_blocks_expected{account_id=\"$account_id\",job=\"$job\"}",
     "legendFormat": "Expected"
    },
    {
     "expr": "near_validators_blocks_produced{account_id=\"$account_id\",job=\"$job\"}",
     "legendFormat": "Produced"
    }
   ]
  },
  {
   "title": "Sync Lag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "near_final_block_height{job=\"$job\"} - near_block_height_head{job=\"$job\"}",
     "legendFormat": "Difference"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1.0 - node_filesystem_free_bytes{fstype=~\"ext.\"} / node_filesystem_size_bytes{fstype=~\"ext.\"}",
     "legendFormat": "{{job}} - {{device}}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device=~\"en.+|et.+\"}[1m])) by (job)",
     "legendFormat": "recv: {{job}}"
    },
    {
     "expr": "-sum(irate(node_network_transmit_bytes_total{device=~\"en.+|et.+\"}[1m])) by (job)",
     "legendFormat": "sent: {{job}}"
    }
   ]
  },
  {
   "title": "Transaction per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(near_transaction_processed_total{job=\"$job\"}[1m])",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Blocks per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 12 },
   "targets": [
    {
     "expr": "near_blocks_per_minute{job=\"$job\"}",
     "legendFormat": "Blocks"
    }
   ]
  },
  {
   "title": "Gas usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(near_gas_used{job=\"$job\"}[1m])",
     "legendFormat": "Gas"
    }
   ]
  },
  {
   "title": "Epoch Height",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "near_epoch_height{job=\"$job\"}",
     "legendFormat": "Epoch Height"
    }
   ]
  },
  {
   "title": "Total supply",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "near_total_supply{job=\"$job\"} * 0.000000000000000000000001",
     "legendFormat": "NEAR Tokens"
    }
   ]
  },
  {
   "title": "Burning",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(near_balance_burnt{job=\"$job\"}[1m]) * 0.000000000000000000000001",
     "legendFormat": "NEAR Tokens"
    }
   ]
  },
  {
   "title": "RPC Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(near_rpc_total_count{job=\"$job\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Peers data received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(near_peer_data_received_bytes{job=\"$job\"}[1m])",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Avg transaction gas cost",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(near_gas_used{job=\"$job\"}[1m]) / rate(near_transaction_processed_total{job=\"$job\"}[1m])",
     "legendFormat": "Gas"
    }
   ]
  },
  {
   "title": "Total Staked",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "near_validators_stake_total{job=\"$job\"}",
     "legendFormat": "NEAR Tokens"
    }
   ]
  },
  {
   "title": "Active validators",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "near_validator_active_total{job=\"$job\"}",
     "legendFormat": "Count"
    }
   ]
  }
 ]
}