{
 "title": "Near Node Alerts",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Is Validator",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "near_is_validator{job=\"near.node\"}",
     "legendFormat": "State"
    }
   ]
  },
  {
   "title": "Sync Lag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "near_final_block_height{job=\"near.node\"} - near_block_height_head{job=\"near.node\"}",
     "legendFormat": "Difference"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "near_peer_connections_total{job=\"near.node\"}",
     "legendFormat": "Peers"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"near.nost\"} - node_memory_MemAvailable_bytes{job=\"near.nost\"}) / node_memory_MemTotal_bytes{job=\"near.nost\"}",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1.0 - node_filesystem_free_bytes{fstype=~\"ext.\",job=\"near.nost\"} / node_filesystem_size_bytes{fstype=~\"ext.\",job=\"near.nost\"}",
     "legendFormat": "{{job}} - {{device}}"
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "near_validators_chunks_expected{account_id=\"klesh.factory.shardnet.near\",job=\"near.node\"}",
     "legendFormat": "Expected"
    },
    {
     "expr": "near_validators_chunks_produced{account_id=\"klesh.factory.shardnet.near\",job=\"near.node\"}",
     "legendFormat": "Produced"
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "near_validators_blocks_expected{account_id=\"klesh.factory.shardnet.near\",job=\"near.node\"}",
     "legendFormat": "Expected"
    },
    {
     "expr": "near_validators_blocks_produced{account_id=\"klesh.factory.shardnet.near\",job=\"near.node\"}",
     "legendFormat": "Produced"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\",job=\"near.nost\"}[1m])) by (job) / count(node_cpu_seconds_total{mode=\"user\",job=\"near.nost\"}) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device=~\"en.+|et.+\",job=\"near.nost\"}[1m])) by (job)",
     "legendFormat": "recv: {{job}}"
    },
    {
     "expr": "-sum(irate(node_network_transmit_bytes_total{device=~\"en.+|et.+\",job=\"near.nost\"}[1m])) by (job)",
     "legendFormat": "sent: {{job}}"
    }
   ]
  }
 ]
}